var hotelFakeData = [
     {
        "hotelId" :1,
        "id":4,
        "place":"Cox's Bazar",
        "name" : "Hotel The Cox Today",
        "img":"https://imgur.com/oiY6GaM.png",
        "guest" : "4",
        "bedrooms" : "2",
        "beds" : "2",
        "baths" : "2",
        "kitchen" : "With Air conditioning Kitchen",
        "flexibility":"Cancellation Flexibility Available...",
        "rating" : "4.5 (20)",
        "star":"https://imgur.com/xdaXFso.png",
        "price" : "52"
    },
    {
        "hotelId" :1,
        "id":5,
        "place":"Cox's Bazar",
        "name" : "Long Beach Hotel",
        "img":"https://imgur.com/TcZuWyd.png",
        "guest" : "4",
        "bedrooms" : "2",
        "beds" : "3",
        "baths" : "3",
        "kitchen" : "With Air conditioning Kitchen",
        "flexibility":"Cancellation Flexibility Available...",
        "rating" : "4.8 (25)",
        "star":"https://imgur.com/xdaXFso.png",
        "price" : "40"
    },
    {
        "hotelId" :1,
        "id":6,
        "place":"Cox's Bazar",
        "name" : "Hotel Sea Crown",
        "img":"https://imgur.com/J3FrR9w.png",
        "guest" : "3",
        "bedrooms" : "2",
        "beds" : "2",
        "baths" : "2",
        "kitchen" : "With Air conditioning Kitchen",
        "flexibility":"Cancellation Flexibility Available...",
        "rating" : "4.5 (15)",
        "star":"https://imgur.com/xdaXFso.png",
        "price" : "55"
    },
    {
        "hotelId" :2,
        "id":7,
        "place":"Sreemangal",
        "name" : "Hotel Merina Sreemangal",
        "img":"https://imgur.com/oiY6GaM.png",
        "guest" : "4",
        "bedrooms" : "2",
        "beds" : "2",
        "baths" : "2",
        "kitchen" : "With Air conditioning Kitchen",
        "flexibility":"Cancellation Flexibility Available...",
        "rating" : "4.5 (20)",
        "star":"https://imgur.com/xdaXFso.png",
        "price" : "52"
    },
    {
        "hotelId" :2,
        "id":8,
        "place":"Sreemangal",
        "name" : "Green Leaf Guest House",
        "img":"https://imgur.com/TcZuWyd.png",
        "guest" : "4",
        "bedrooms" : "2",
        "beds" : "3",
        "baths" : "3",
        "kitchen" : "With Air conditioning Kitchen",
        "flexibility":"Cancellation Flexibility Available...",
        "rating" : "4.8 (25)",
        "star":"https://imgur.com/xdaXFso.png",
        "price" : "40"
    },
    {
        "hotelId" :2,
        "id":9,
        "place":"Sreemangal",
        "name" : "Grand Sultan Tea Resort & Golf",
        "img":"https://imgur.com/J3FrR9w.png",
        "guest" : "3",
        "bedrooms" : "2",
        "beds" : "2",
        "baths" : "2",
        "kitchen" : "With Air conditioning Kitchen",
        "flexibility":"Cancellation Flexibility Available...",
        "rating" : "4.5 (15)",
        "star":"https://imgur.com/xdaXFso.png",
        "price" : "55"
    },
    {
        "hotelId" :3,
        "id":10,
        "place":"Sundarban",
        "name" : "Sunderban Tiger Camp",
        "img":"https://imgur.com/oiY6GaM.png",
        "guest" : "4",
        "bedrooms" : "2",
        "beds" : "2",
        "baths" : "2",
        "kitchen" : "With Air conditioning Kitchen",
        "flexibility":"Cancellation Flexibility Available...",
        "rating" : "4.5 (20)",
        "star":"https://imgur.com/xdaXFso.png",
        "price" : "52"
    },
    {
        "hotelId" :3,
        "id":11,
        "place":"Sundarban",
        "name" : "hotel East Coast",
        "img":"https://imgur.com/TcZuWyd.png",
        "guest" : "4",
        "bedrooms" : "2",
        "beds" : "3",
        "baths" : "3",
        "kitchen" : "With Air conditioning Kitchen",
        "flexibility":"Cancellation Flexibility Available...",
        "rating" : "4.8 (25)",
        "star":"https://imgur.com/xdaXFso.png",
        "price" : "40"
    },
    {
        "hotelId" :3,
        "id":12,
        "place":"Sundarban",
        "name" : "Hotel Deepak",
        "img":"https://imgur.com/J3FrR9w.png",
        "guest" : "3",
        "bedrooms" : "2",
        "beds" : "2",
        "baths" : "2",
        "kitchen" : "With Air conditioning Kitchen",
        "flexibility":"Cancellation Flexibility Available...",
        "rating" : "4.5 (15)",
        "star":"https://imgur.com/xdaXFso.png",
        "price" : "55"
    }

];
export default hotelFakeData;